### ISSUE TITLE
Running e2e tests shows an NPM error even though all tests pass

### ISSUE THREAD

**Issue by erinknight242** [HeadspringLabs/Totem#15]
Determine how we can configure these scripts to not show termination as an error after running the tests.

Repro steps:

1. Run 'npm run e2e' from the src/Totem folder
2. All tests should pass, but still see the NPM error shown below:

![image](https://user-images.githubusercontent.com/3969554/64972319-b408f980-d86e-11e9-8a3b-d59eba6d6f96.png)

**Comment by saa14** [comment]
Should be resolved with #38
