### ISSUE TITLE
Use warning color for deprecation warning text

### ISSUE THREAD

**Issue by erinknight242** [HeadspringLabs/Totem#87]
Currently the deprecation warning appears in the same font style as the "Message is Valid" text. It should instead be on a new line like message errors, and in the orange warning color.

![image](https://user-images.githubusercontent.com/3969554/66785989-7e265780-eea4-11e9-8f97-b8555880762c.png)

**Comment by najeraz** [comment]
Fixed at https://github.com/HeadspringLabs/Totem/pull/86
