### ISSUE TITLE
Question: How does the provider know the contract IDs?

### ISSUE THREAD

**Issue by heymega** [HeadspringLabs/Totem#91]
How would the providers know the contract IDs of all the consumer's contracts?

Unless I'm mistaken, every time you add a consumer contract you would then need to add the test to the associated provider and include the new contract ID.

The example from the README doesn't have anything that links this contract with a consumer and provider.
```
{
    "Contract": {
        "type": "object",
        "properties": {
            "OrderId": {
                "$ref": "#/Guid"
            },
            "ItemName": {
                "type": "string"
            },
            "Total" : {
                "type": "integer"
            },
            "Timestamp": {
                "type": "string",
                "format": "date-time",
                "example": "2019-01-01T18:14:29Z"
            }
        }
    },
    "Guid": {
        "type": "string",
        "pattern": "^(([0-9a-f]){8}-([0-9a-f]){4}-([0-9a-f]){4}-([0-9a-f]){4}-([0-9a-f]){12})$",
        "minLength": 36,
        "maxLength": 36,
        "example": "01234567-abcd-0123-abcd-0123456789ab"
    }
}
```

Have I interpreted that correctly?

**Comment by adamcowart-hs** [comment]
@heymega Thanks for the question.

The typical workflow for creating contracts would be:
1. The producer creates the contract definition via the Totem UI (and then writes a test to verify that their code produces a message that matches the contract)
2. The producer sends the link for the contract details to any known consumers (see screenshot below)
3. The consumer follows the link to the contract details page, which contains the contract id

Additionally, there is a list view in the UI for all defined contracts:
![image (6)](https://user-images.githubusercontent.com/55255141/70679041-9672e280-1c59-11ea-9074-6bd27e3089ec.png)

If you click on the details link, you can view the details of the contract which includes the contract id:
![image (7)](https://user-images.githubusercontent.com/55255141/70679078-ba362880-1c59-11ea-8a54-c657eda6bc99.png)

As contracts are defined, Totem acts as documentation of all contracts that are being produced.  Consumers can check to see if any of the existing contracts contain the data they need.

Let us know if you have any follow up questions.

Thanks!

**Comment by heymega** [comment]
That's great - Thank you for the explanation.
